#!/usr/bin/env ruby
#
# Shortcuttr - generator for executable shortcuts
#
require 'fileutils'

SCRIPT = File.join "#{ENV['HOME']}/github/ruby-scripts/system/bin", ARGV.first.to_s
File.open SCRIPT, 'w', 0755 do |f|
	f.puts %Q[
#!/usr/bin/bash
# This executable shortcut was generated by Stephen Benner, a truly lazy programmer
#{ARGV[1].to_s}
]
end
FileUtils.symlink SCRIPT, File.join('/usr/local/bin', ARGV.first.to_s), verbose: true